//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tischfussball_TurnierManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tischfussball_TurnierManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning Strength.
        /// </summary>
        public static string ColBeginningStrength {
            get {
                return ResourceManager.GetString("ColBeginningStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string ColFirstName {
            get {
                return ResourceManager.GetString("ColFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games played.
        /// </summary>
        public static string ColGamesPlayed {
            get {
                return ResourceManager.GetString("ColGamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal difference.
        /// </summary>
        public static string ColGoaldifference {
            get {
                return ResourceManager.GetString("ColGoaldifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string ColIsActive {
            get {
                return ResourceManager.GetString("ColIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string ColLastName {
            get {
                return ResourceManager.GetString("ColLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string ColPlayer {
            get {
                return ResourceManager.GetString("ColPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string ColPoints {
            get {
                return ResourceManager.GetString("ColPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points per game.
        /// </summary>
        public static string ColPointsPerGame {
            get {
                return ResourceManager.GetString("ColPointsPerGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string ColRank {
            get {
                return ResourceManager.GetString("ColRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startnumber.
        /// </summary>
        public static string ColStartNumber {
            get {
                return ResourceManager.GetString("ColStartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals.
        /// </summary>
        public static string Goals {
            get {
                return ResourceManager.GetString("Goals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string LabDate {
            get {
                return ResourceManager.GetString("LabDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string LabDescription {
            get {
                return ResourceManager.GetString("LabDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string LabName {
            get {
                return ResourceManager.GetString("LabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Tournament.
        /// </summary>
        public static string MICreateTournament {
            get {
                return ResourceManager.GetString("MICreateTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string MIEnglish {
            get {
                return ResourceManager.GetString("MIEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Tournament in XLS.
        /// </summary>
        public static string MIExportInXLS {
            get {
                return ResourceManager.GetString("MIExportInXLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MIFile {
            get {
                return ResourceManager.GetString("MIFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string MIGerman {
            get {
                return ResourceManager.GetString("MIGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string MILanguage {
            get {
                return ResourceManager.GetString("MILanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Tournament.
        /// </summary>
        public static string MILoad {
            get {
                return ResourceManager.GetString("MILoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw a new round.
        /// </summary>
        public static string MINewRound {
            get {
                return ResourceManager.GetString("MINewRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round.
        /// </summary>
        public static string MIRound {
            get {
                return ResourceManager.GetString("MIRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Tournament.
        /// </summary>
        public static string MISave {
            get {
                return ResourceManager.GetString("MISave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save  Tournament As....
        /// </summary>
        public static string MISaveAs {
            get {
                return ResourceManager.GetString("MISaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MISettings {
            get {
                return ResourceManager.GetString("MISettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament.
        /// </summary>
        public static string MITournament {
            get {
                return ResourceManager.GetString("MITournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Tournament.
        /// </summary>
        public static string NewTournamentName {
            get {
                return ResourceManager.GetString("NewTournamentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foosball Tournament Manager.
        /// </summary>
        public static string ProgramTitle {
            get {
                return ResourceManager.GetString("ProgramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RefreshDrawPostRound {
            get {
                return ResourceManager.GetString("RefreshDrawPostRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redraw round .
        /// </summary>
        public static string RefreshDrawPreRound {
            get {
                return ResourceManager.GetString("RefreshDrawPreRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and .
        /// </summary>
        public static string TeamDisplayNameConnector {
            get {
                return ResourceManager.GetString("TeamDisplayNameConnector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance List.
        /// </summary>
        public static string TIAttendenceList {
            get {
                return ResourceManager.GetString("TIAttendenceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw.
        /// </summary>
        public static string TIDraw {
            get {
                return ResourceManager.GetString("TIDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking.
        /// </summary>
        public static string TIRanking {
            get {
                return ResourceManager.GetString("TIRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournament Settings.
        /// </summary>
        public static string TITournamentSettings {
            get {
                return ResourceManager.GetString("TITournamentSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
